### ISSUE TITLE
package request: atlas-devel

### ISSUE THREAD

**Issue by DaHoopster** [nanobox-io/nanobox-pkgsrc-base#31]
This package is needed to build SciPy and NumPy

**Comment by notxarb** [comment]
hmm, I thought I got those to compile using `lapack` and `blas`. I can take a look into getting a package for `atlas`.

**Comment by notxarb** [comment]
`atlas` should be available now.

**Comment by DaHoopster** [comment]
thanks, will try to build the package later today!

**Comment by DaHoopster** [comment]
Hmm, I added the following lines in my Boxfile.yml:
```
extra_packages:
    - atlas-devel
```

But `nanobox run` errored out with the following output:
```
Building runtime :
  ✓ Starting docker container
  ! Preparing environment for build
    - Copying ssh keys into the build environment...
    - Setting up directories and permissions...
    - Cloning engine :
      Cloning into 'engine'...
      remote: Counting objects: 731, done.
      remote: Compressing objects: 100% (31/31), done.
      remote: Total 731 (delta 24), reused 44 (delta 19), pack-reused 678
      Receiving objects: 100% (731/731), 120.61 KiB | 0 bytes/s, done.
      Resolving deltas: 100% (315/315), done.
      Checking connectivity... done.
    
    - Cleaning up any previous builds...
    - Updating pkg database...
    - Installing user-requested packages :
      calculating dependencies... done.
      nothing to do.
    
    ! FAILED TO INSTALL PACKAGES !
    
    Exit
     1
    
    Command
     su - gonano -c "export PATH=\"/data/sbin:/data/bin:/opt/gonano/sbin:/opt/gonano/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\";       stdbuf -o0         siphon --prefix '  ' --           bash -c \"/data/bin/pkgin -y in atlas-devel\"
     "
    
    Output
      calculating dependencies... done.
       nothing to do.
    

Error   : failed to execute hook (setup) on bc1a37a21ee5664ee3b0acdf2f791d663b622b2526642771775ba617ea3c1479: util:Exec:/opt/nanobox/hooks/setup: bad exit code(1): 
Context : failed to build the code -> failed to run the (build)setup hook
```

Any ideas what went wrong?

**Comment by tylerflint** [comment]
Can you try adding as just "atlas"?

**Comment by DaHoopster** [comment]
Thanks, just `atlas` fixes the aforementioned error. But I got a different one when building `scipy`:

```
Installing collected packages: scipy, scikit-learn, python-dateutil, pytz, pandas
  Running setup.py install for scipy ... error
    Complete output from command /data/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p7is9290/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-eayr87ym-record/install-record.txt --single-version-externally-managed --compile:
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['/data/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    openblas_info:
      libraries  not found in ['/data/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/data/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/data/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /data/lib/python3.6/site-packages/numpy/distutils/system_info.py:1521: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    blas_info:
      libraries blas not found in ['/data/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /data/lib/python3.6/site-packages/numpy/distutils/system_info.py:1530: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      warnings.warn(BlasNotFoundError.__doc__)
    blas_src_info:
      NOT AVAILABLE
    
    /data/lib/python3.6/site-packages/numpy/distutils/system_info.py:1533: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      warnings.warn(BlasSrcNotFoundError.__doc__)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p7is9290/scipy/setup.py", line 230, in <module>
        setup_package()
      File "/tmp/pip-build-p7is9290/scipy/setup.py", line 227, in setup_package
        setup(**metadata)
      File "/data/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-p7is9290/scipy/setup.py", line 170, in configuration
        config.add_subpackage('scipy')
      File "/data/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/data/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/data/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 12, in configuration
        config.add_subpackage('integrate')
      File "/data/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/data/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/data/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/integrate/setup.py", line 12, in configuration
        blas_opt = get_info('blas_opt',notfound_action=2)
      File "/data/lib/python3.6/site-packages/numpy/distutils/system_info.py", line 350, in get_info
        return cl().get_info(notfound_action)
      File "/data/lib/python3.6/site-packages/numpy/distutils/system_info.py", line 509, in get_info
        raise self.notfounderror(self.notfounderror.__doc__)
    numpy.distutils.system_info.BlasNotFoundError:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
```

Does the error indicate `atlas` isn't working or does it mean I need more packages?
